# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Basic"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A blue bootstrap theme"
homepage = "http://sanzorb.com/"
tags = [bootstrap, html, css, minify, simple, navbar, clean, blog, portfolio]
features = [works as a blog theme, works as a portfolio theme, made with bootstrap 4]
min_version = "0.0.1"

[author]
  name = "San Glover"
  homepage = "http://sanzorb.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
